const languages = {
    MX: {
        passwords: 'Contraseñas',
        passwordswifi: 'Contraseñas de WiFi',
        notes: 'Notas',
        logout: 'Cerrar Sesión',
        copy: 'Copiar al portapapeles',
        gosite: 'Ir al sitio',
        deleteLabel: 'Eliminar',
        instructions: 'Haz clic en una contraseña',
        titleEdit: 'Editar contraseña',
        showPassword: 'Mostrar contraseña',
        hidePassword: 'Ocultar contraseña',
        notesPlaceholder: 'Deje notas que sean utiles para esta contraseña emails, recordatorios etc.',
        usernameLabel: 'Username',
        passwordLabel: 'Contraseña',
        notesLabel: 'Notas',
        pickColorLabel: 'Color de contraseña',
        closeLabel: 'Cerrar',
        saveLabel: 'Guardar',
        confirmDelete: '¿Quieres eliminar esta contraseña?',
        yesLabel: 'Si',
        noLabel: 'No',
        nameLabel: 'Nombre',
        urlPlaceholder: 'Ejemplo: https://www.google.com',
        namePlaceholder: 'Nombre de la contraseña',
        passwordPlaceholder: 'Tu contraseña super secreta ;)',
    }, 
    EN: {
        passwords: 'Passwords',
        passwordswifi: 'WiFi passwords',
        notes: 'Notes',
        logout: 'Logout',
        copy: 'Copy to clipboard',
        gosite: 'Go the site',
        deleteLabel: 'Delete',
        instructions: 'Click on a password',
        titleEdit: 'Edit password',
        showPassword: 'Show password',
        hidePassword: 'Hide password',
        notesPlaceholder: 'Leave notes that are useful for this password emails, reminders etc.',
        usernameLabel: 'Username',
        passwordLabel: 'Password',
        notesLabel: 'Notes',
        pickColorLabel: 'Password color',
        closeLabel: 'Close',
        saveLabel: 'Save',
        confirmDelete: 'You want to delete this password?',
        yesLabel: 'Yes',
        noLabel: 'No',
        nameLabel: 'Name',
        urlPlaceholder: 'Example: https://www.google.com',
        namePlaceholder: 'Name of the password',
        passwordPlaceholder: 'Your super secret password ;)',
    },
    FR: {
        passwords: 'Mots de passe',
        passwordswifi: 'Mots de passe Wi-Fi',
        notes: 'Notes',
        logout: 'Fermer la session',
        copy: 'Copier dans le presse-papier',
        gosite: 'Aller sur le site',
        deleteLabel: 'Retirer',
        instructions: 'Cliquez sur un mot de passe',
        titleEdit: 'Éditer mot de passe',
        showPassword: 'Montrer le mot de passe',
        hidePassword: 'Masquer le mot de passe',
        notesPlaceholder: 'Laissez des notes utiles pour ce mot de passe, les e-mails, les rappels, etc.',
        usernameLabel: "Nom d'utilisateur",
        passwordLabel: 'Mot de passe',
        notesLabel: 'Notes',
        pickColorLabel: 'Couleur de mot de passe',
        closeLabel: 'Proche',
        saveLabel: 'Sauvegarder',
        confirmDelete: 'Voulez-vous supprimer ce mot de passe?',
        yesLabel: 'Oui',
        noLabel: 'Non',
        nameLabel: 'Nom',
        urlPlaceholder: 'Exemple: https://www.google.com',
        namePlaceholder: 'Nom du mot de passe',
        passwordPlaceholder: 'Tu mot de passe super secrète ;)',
    }
}

export function getWord(language, word) {
    return languages[language][word]
}