const languages = {
    MX: {
        passwords: 'Contraseñas',
        passwordswifi: 'Contraseñas de WiFi',
        notes: 'Notas',
        logout: 'Cerrar Sesión',
        copy: 'Copiar al portapapeles',
        gosite: 'Ir al sitio',
        delete: 'Eliminar',
        instructions: 'Haz clic en una contraseña',
        titleEdit: 'Editar contraseña',
        showPassword: 'Mostrar contraseña',
        hidePassword: 'Ocultar contraseña',
        notesPlaceholder: 'Deje notas que sean utiles para esta contraseña emails, recordatorios etc.',
        usernameLabel: 'Username',
        passwordLabel: 'Contraseña',
        notesLabel: 'Notas',
    }, 
    EN: {
        passwords: 'Passwords',
        passwordswifi: 'WiFi passwords',
        notes: 'Notes',
        logout: 'Logout',
        copy: 'Copy to clipboard',
        gosite: 'Go the site',
        delete: 'Delete',
        instructions: 'Click on a password',
        titleEdit: 'Edit password',
        showPassword: 'Show password',
        hidePassword: 'Hide password',
        notesPlaceholder: 'Leave notes that are useful for this password emails, reminders etc.',
        usernameLabel: 'Username',
        passwordLabel: 'Password',
        notesLabel: 'Notes',
    },
    FR: {
        passwords: 'Mots de passe',
        passwordswifi: 'Mots de passe Wi-Fi',
        notes: 'Notes',
        logout: 'Fermer la session',
        copy: 'Copier dans le presse-papier',
        gosite: 'Aller sur le site',
        delete: 'Retirer',
        instructions: 'Cliquez sur un mot de passe',
        titleEdit: 'Éditer mot de passe',
        showPassword: 'Montrer le mot de passe',
        hidePassword: 'Masquer le mot de passe',
        notesPlaceholder: 'Laissez des notes utiles pour ce mot de passe, les e-mails, les rappels, etc.',
        usernameLabel: "Nom d'utilisateur",
        passwordLabel: 'Mot de passe',
        notesLabel: 'Notes',
    }
}

export function getWord(language, word) {
    return languages[language][word]
}